auto switch locale system
qbcore-framework/qb-drugs pull request #91
Opened 2022-09-10 15:09 UTC by buddizer

**Describe Pull request**
adding auto switch locale system

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
- Does your code fit the style guidelines? yes
- Does your PR fit the contribution guidelines? yes

2022-09-12 08:24 UTC, tom-osborne requested changes

2022-09-12 08:24 UTC, tom-osborne commented on fxmanifest.lua
> +    'locales/en.lua', -- Change this to your preferred language
The comment can be removed here since the user no longer has to change this.

2022-09-13 22:01 UTC, buddizer commented
Corrected

2022-09-13 23:03 UTC, D4isDAVID approved these changes
LGTM

2022-09-14 07:58 UTC, tom-osborne approved these changes

2022-09-14 07:58 UTC, merged